- name: check Jaeger operator
  stat: path={{playbook_dir}}/roles/istio_deploy/files/jo-sub.yaml
  register: out

- name: deploy Jaeger operator
  command: oc apply -f {{ playbook_dir }}/roles/istio_deploy/files/files/jo-sub.yaml
  when: out|changed
