- name: process elasticsearch operator template
  template:
    src: eo-sub.yaml.j2
    dest: "/tmp/eo-sub.yaml"
  
- name: deploy elasticsearch operator 
  command: oc apply -f /tmp/eo-sub.yaml
  register: oc_res
- debug: var=oc_res.stdout_lines
