- name: check Jaeger operator
  stat: path={{playbook_dir}}/roles/istio_deploy/files/jo-sub.yaml
  register: out

- name: deploy Jaeger operator
  command: oc apply -f {{ playbook_dir }}/roles/istio_deploy/files/jo-sub.yaml
  register: oc_res
- debug: var=oc_res.stdout_lines
  when: out|changed
