apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
spec:
  origins:
  - jwt:
      audiences:
      - istio
      issuer: https://sso.ocp4.example.com/auth/realms/istio
      jwksUri: https://sso.apps.ocp4.example.com/auth/realms/istio/protocol/openid-connect/certs
  peers:
  - mtls: {}
  principalBinding: USE_ORIGIN
  targets:
  - name: httpbin
